version: "3"
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    container_name: postgres
    volumes:
      - creddig_db:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/
    env_file:
      - ./.env
    # Postgres ports should never be exposed in production
    # uncomment the ports only for development reasons
    ports:
      - "5432:${DBPORT}"
volumes:
  creddig_db:
